In [1]:
import os
import pandas as pd
import re

In [3]:
df.to_csv("geolocation_data.csv")

In [2]:
df = pd.read_csv("geolocation_data.csv")
df

,Unnamed: 0,Title,Link,Context
0,0,Krewe du Vieux 2018: Take a virtual tour of th...,http://www.nola.com/mardi_gras_nola/2018/01/ta...,This area formed the heart of the plantation o...
1,1,Turkey shells Syrian city as it pushes into Ku...,http://www.eastoregonian.com/turkey-shells-syr...,BEIRUT (AP) � A Kurdish militia spokesman says...
2,2,"A new development in Gainesville, Va., provide...",https://www.washingtonpost.com/realestate/a-ta...,Southern design Buy Photo : Exteriors are vary...
3,3,Laura Ingraham takes an Easter break amid Davi...,http://bangordailynews.com/2018/03/31/news/nat...,"Cleve R. Wootson Jr., The Washington Post Marc..."
4,4,Perm Secretary Launches Book for Africa’s Deve...,http://www.thisdaylive.com/index.php/2018/03/3...,"Former Permanent Secretary, Federal Ministry o..."
...,...,...,...,...
195,195,Incoming MFSA chairman accuses Deutsche Bank o...,https://www.maltatoday.com.mt/news/national/85...,Incoming Malta Financial Services Authority ch...
196,196,EW Nutrition and ICON Form a Strategic Partner...,http://www.adnkronos.com/immediapress/pr-newsw...,EW Nutrition acquires 51% of the shares in ICO...
197,197,A question of diversity: how fashion is ditchi...,http://www.watoday.com.au/world/a-question-of-...,"""We want to be held accountable,"" she said in ..."
198,198,Altnagelvin’s new health and well-being hub opens,https://www.derryjournal.com/news/altnagelvin-...,A new Health and Wellbeing Campus has opened a...
199,199,MIL-OSI USA: Diaz-Balart Speaks at Immokalee T...,https://foreignaffairs.co.nz/2018/03/30/mil-os...,Source: United States House of Representatives...

In [5]:
df.drop(columns=["Unnamed: 0","Link"], axis=1, inplace=True)
df

,Title,Context
0,Krewe du Vieux 2018: Take a virtual tour of th...,This area formed the heart of the plantation o...
1,Turkey shells Syrian city as it pushes into Ku...,BEIRUT (AP) � A Kurdish militia spokesman says...
2,"A new development in Gainesville, Va., provide...",Southern design Buy Photo : Exteriors are vary...
3,Laura Ingraham takes an Easter break amid Davi...,"Cleve R. Wootson Jr., The Washington Post Marc..."
4,Perm Secretary Launches Book for Africa’s Deve...,"Former Permanent Secretary, Federal Ministry o..."
...,...,...
195,Incoming MFSA chairman accuses Deutsche Bank o...,Incoming Malta Financial Services Authority ch...
196,EW Nutrition and ICON Form a Strategic Partner...,EW Nutrition acquires 51% of the shares in ICO...
197,A question of diversity: how fashion is ditchi...,"""We want to be held accountable,"" she said in ..."
198,Altnagelvin’s new health and well-being hub opens,A new Health and Wellbeing Campus has opened a...
199,MIL-OSI USA: Diaz-Balart Speaks at Immokalee T...,Source: United States House of Representatives...

In [7]:
import spacy
from spacy import displacy

NER = spacy.load("en_core_web_sm")

In [8]:
def contextToloc(text:str):
    text = NER(text)
    loc = []
    for word in text.ents:
        if word.label_ == "GPE":
            loc.append(word.text)
    return loc

In [9]:
df["Locations"] = df["Context"].apply(contextToloc)
df

,Title,Context,Locations
0,Krewe du Vieux 2018: Take a virtual tour of th...,This area formed the heart of the plantation o...,"[Dubreuil, Dubreuil]"
1,Turkey shells Syrian city as it pushes into Ku...,BEIRUT (AP) � A Kurdish militia spokesman says...,"[Turkey, Syria, Turkey, Turkey, Afrin, Britain]"
2,"A new development in Gainesville, Va., provide...",Southern design Buy Photo : Exteriors are vary...,"[Charleston, Norbury, Granville, Somerville, N..."
3,Laura Ingraham takes an Easter break amid Davi...,"Cleve R. Wootson Jr., The Washington Post Marc...","[Parkland, Florida, California, San Marcos, Am..."
4,Perm Secretary Launches Book for Africa’s Deve...,"Former Permanent Secretary, Federal Ministry o...","[Abuja, Nigeria, Nigeria, Olaopa]"
...,...,...,...
195,Incoming MFSA chairman accuses Deutsche Bank o...,Incoming Malta Financial Services Authority ch...,"[Malta, UK, Malta, Malta, Germany, London, Mal..."
196,EW Nutrition and ICON Form a Strategic Partner...,EW Nutrition acquires 51% of the shares in ICO...,"[Turkey, Ufuk Yilmaz, Ankara, Turkey, Visbek, ..."
197,A question of diversity: how fashion is ditchi...,"""We want to be held accountable,"" she said in ...","[Los Angeles, London, Spain, South Africa, Tai..."
198,Altnagelvin’s new health and well-being hub opens,A new Health and Wellbeing Campus has opened a...,"[Northern Ireland, the Republic and Northern T..."
199,MIL-OSI USA: Diaz-Balart Speaks at Immokalee T...,Source: United States House of Representatives...,"[United States, Collier County’s, Florida, Cou..."

In [10]:
def remove_dup(arr_input: list) ->list:
    unique_list = []
    for item in arr_input:
        if item not in unique_list:
            unique_list.append(item)
    return unique_list

In [11]:
df["Locations"] = df["Locations"].apply(remove_dup)
df

,Title,Context,Locations
0,Krewe du Vieux 2018: Take a virtual tour of th...,This area formed the heart of the plantation o...,[Dubreuil]
1,Turkey shells Syrian city as it pushes into Ku...,BEIRUT (AP) � A Kurdish militia spokesman says...,"[Turkey, Syria, Afrin, Britain]"
2,"A new development in Gainesville, Va., provide...",Southern design Buy Photo : Exteriors are vary...,"[Charleston, Norbury, Granville, Somerville, M..."
3,Laura Ingraham takes an Easter break amid Davi...,"Cleve R. Wootson Jr., The Washington Post Marc...","[Parkland, Florida, California, San Marcos, Am..."
4,Perm Secretary Launches Book for Africa’s Deve...,"Former Permanent Secretary, Federal Ministry o...","[Abuja, Nigeria, Olaopa]"
...,...,...,...
195,Incoming MFSA chairman accuses Deutsche Bank o...,Incoming Malta Financial Services Authority ch...,"[Malta, UK, Germany, London]"
196,EW Nutrition and ICON Form a Strategic Partner...,EW Nutrition acquires 51% of the shares in ICO...,"[Turkey, Ufuk Yilmaz, Ankara, Visbek, Germany,..."
197,A question of diversity: how fashion is ditchi...,"""We want to be held accountable,"" she said in ...","[Los Angeles, London, Spain, South Africa, Tai..."
198,Altnagelvin’s new health and well-being hub opens,A new Health and Wellbeing Campus has opened a...,"[Northern Ireland, the Republic and Northern T..."
199,MIL-OSI USA: Diaz-Balart Speaks at Immokalee T...,Source: United States House of Representatives...,"[United States, Collier County’s, Florida, Cou..."

In [12]:
filtered_df = df[df['Locations'].apply(lambda x: 'London' in x)]

In [13]:
# Print the filtered DataFrame
print(filtered_df)

                                                 Title  \
23   The Latest: Russian envoys leave Washington to...
38   Artists hope U.S. court ruling will help them ...
43   The train as a replacement for short European ...
45   Daughter of ex-spy poisoned in UK says case is...
62   Woman, 20, killed after bullet ricocheted off ...
75                    Knife crime is surging in London
88   Flying with a pet? Program created to ensure s...
168  Zimbabwe:British Airways Rejects Plea for Lond...
188  JJ McNamara invited to Dublin International Pi...
195  Incoming MFSA chairman accuses Deutsche Bank o...
197  A question of diversity: how fashion is ditchi...

                                               Context  \
23   LONDON The Latest on the nerve agent poisoning...
38   Could a landmark compensation award by a New Y...
43   The first direct Eurostar train to Amsterdam a...
45   Yulia Skripal made her first public comment on...
62   A young woman was killed when a bullet ricoche...
75   The press is alarmed. Last weekend the Sunday ...
88   After a spate of incidents last month about an...
168  By Staff Reporter. The Herald Tourism minister...
188  Chances are, if you grew up in a house where t...
195  Incoming Malta Financial Services Authority ch...
197  "We want to be held accountable," she said in ...

                                             Locations
23   [LONDON, Britain, Washington, the United State...
38   [New York, the United States, WASHINGTON, Wash...
43   [Amsterdam, London, Brussels, Paris, Berlin, H...
45   [Britain, Salisbury, Russia, Moscow, London, Y...
62   [Montana, Grannum, north west, London, Kilburn...
75   [London, New York, New York’s, England, Wales,...
88                  [Japan, Kansas City, U.S., London]
168          [London, UK, Britain, Zimbabwe, Zimndaba]
188  [Rathbeggan, Dunshaughlin, London, Dublin, JJ,...
195                       [Malta, UK, Germany, London]
197  [Los Angeles, London, Spain, South Africa, Tai...

In [19]:
from geopy.geocoders import OpenCage

In [20]:
api_key = 'ec0d78b8f69740de8e63468bdd32210b'  # Replace 'YOUR_API_KEY' with your actual API key
geolocator = OpenCage(api_key)

In [21]:
def get_lat_long(location):
    try:
        # Get location information from Nominatim
        location_info = geolocator.geocode(location)
        if location_info:
            return location_info.latitude, location_info.longitude
        else:
            return None, None
    except Exception as e:
        print(f"Error occurred: {e}")
        return None, None

In [22]:
# Function to convert locations to latitude and longitude
def convert_to_lat_long(locations):
    latitudes = []
    longitudes = []
    for location in locations:
        lat, long = get_lat_long(location)
        latitudes.append(lat)
        longitudes.append(long)
    return latitudes, longitudes

In [23]:
df[['Latitude', 'Longitude']] = df['Locations'].apply(lambda x: pd.Series(convert_to_lat_long(x)))

In [24]:
df.head()

,Title,Context,Locations,Latitude,Longitude
0,Krewe du Vieux 2018: Take a virtual tour of th...,This area formed the heart of the plantation o...,[Dubreuil],[-20.3000855],[57.6023555]
1,Turkey shells Syrian city as it pushes into Ku...,BEIRUT (AP) � A Kurdish militia spokesman says...,"[Turkey, Syria, Afrin, Britain]","[38.9597594, 34.6401861, 36.5083795, 54.3151594]","[34.9249653, 39.0494106, 36.870089, -1.9181532]"
2,"A new development in Gainesville, Va., provide...",Southern design Buy Photo : Exteriors are vary...,"[Charleston, Norbury, Granville, Somerville, M...","[32.7884363, 51.4110663, 48.8376296, 42.387596...","[-79.9399309, -0.1224869, -1.5959177, -71.0994..."
3,Laura Ingraham takes an Easter break amid Davi...,"Cleve R. Wootson Jr., The Washington Post Marc...","[Parkland, Florida, California, San Marcos, Am...","[26.3100794, 27.7567667, 36.7014631, 29.882643...","[-80.23727, -81.4639835, -118.755997, -97.9405..."
4,Perm Secretary Launches Book for Africa’s Deve...,"Former Permanent Secretary, Federal Ministry o...","[Abuja, Nigeria, Olaopa]","[9.0643305, 9.6000359, None]","[7.4892974, 7.9999721, None]"

In [25]:
df.to_csv('final_geo.csv', index=False)